fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" 
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true

[font]
size = 12
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Normal"

[[font.bold]]
family = "JetBrainsMono Nerd Font Propo"
style = "W600"

