enter_accept = true

[stats]

common_subcommands = [
  "bun",
  "cargo",
  "composer",
  "docker",
  "kubectl",
  "npm",
  "pnpm",
 ]

ignored_commands = [
  "nvim",
  "vim",
  "cd",
  "ls",
  "vi"
]

[keys]
# Defaults to true. If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
# scroll_exits = false

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true

[preview]
## which preview strategy to use to calculate the preview height (respects max_preview_height).
## possible values: auto, static
## auto: length of the selected command.
## static: length of the longest command stored in the history.
# strategy = "auto"

[daemon]
## Enables using the daemon to sync. Requires the daemon to be running in the background. Start it with `atuin daemon`
# enabled = false

