format = """\
[](#96CDFB)\
($directory)\
[ ](#96CDFB)\
[](#DDB6F2)\
$git_branch\
$git_status\
[ ](#DDB6F2)\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
\n$character\
"""

# Disable the blank line at the beginning of the prompt
add_newline = true

# Command timeout
command_timeout = 3600000

[fill]
symbol = ' '

[character]
success_symbol = "[❯](#C9CBFF)"
error_symbol = "[❯](#F28FAD)"
vimcmd_symbol = "[❮](#ABE9B3)"

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[󱗞 $user](fg:$style) ' # Mustache before the username
disabled = false
show_always = true

# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style)"
read_only = "  "
style = "fg:#1E1D2D bg:#96CDFB"
truncation_symbol = "…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = " took [ $duration]($style) "
style = 'fg:#D9E0EE'
min_time = 1_000

[git_branch]
symbol = " "
style = "fg:#1E1D2D bg:#DDB6F2"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#1E1D2D bg:#DDB6F2"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
disabled = true
symbol = " "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))](fg:#FF9E3B)($style)'
symbol = " "
version_format = "${raw}"

[java]
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:#FFA066)]($style)'
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:#DCD7BA)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#87a987)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF9E3B)]($style)'

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
format = '[[   $time ](fg:#8BA4B0)]($style)'
